export const DASHBOARD_ADD            = 'dashboard_add'
export const DASHBOARD_DELETE         = 'dashboard_delete'
export const DASHBOARD_UPDATE         = 'dashboard_update'
export const DASHBOARD_GET_ALL        = 'dashboard_get_all'
export const DASHBOARD_REMOVE_WIDGET  = 'dashboard_remove_widget'
export const DASHBOARD_ADD_WIDGET     = 'dashboard_add_widget'
export const DASHBOARD_ADD_DASHBOARD  = 'dashboard_add_dashboard'